language: rust

# cache: cargo

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

os:
  - linux
  # - osx
  # - windows
rust:
  - 1.40.0
  # - 1.41.0

script:
  - cargo build --verbose --all
  - cargo test --verbose --all -- --nocapture

after_success: |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  make install DESTDIR=../../kcov-build &&
  cd ../.. &&
  rm -rf kcov-master;
  ./kcov-build/usr/local/bin/kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov $(find target/debug -maxdepth 1 -executable -name adr-\*);
  echo "Uploaded code coverage to coveralls" ; fi
