language: rust

# cache: cargo

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

os:
  - linux
  - osx
  - windows
rust:
  - 1.40.0
  - 1.41.0

script:
  - cargo build --verbose --all
  - cargo test --verbose --all -- --nocapture

after_success: |
    [ $TRAVIS_BRANCH = master ] &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    [ "$TRAVIS_OS_NAME" = "linux" ] &&
    wget https://github.com/SimonKagstrom/kcov/archive/master.zip &&
    unzip master.zip && mv kcov-master kcov && mkdir kcov/build && cd kcov/build &&
    cmake .. && make && make install DESTDIR=../built && cd ../.. &&
    ./kcov/built/usr/local/bin/kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov $(find target/debug -maxdepth 1 -executable -name azul-\*) &&
    ./kcov/built/usr/local/bin/kcov --coveralls-id=${TRAVIS_JOB_ID} --merge ./target/kcov-merge ./target/kcov
