<div class="mermaid">
stateDiagram
	[*] --> wip
	wip --> decided: is decided
    decided --> superseded
    cancelled --> [*]

	decided --> cancelled

	wip --> completed: is completed by
	decided --> completed
	completed --> decided: if [wip]

	wip --> cancelled

	completed --> superseded

	completed --> cancelled
	superseded --> cancelled
</div>