name: Rust

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose  
    - name: Run tests
      run: cargo test --verbose